package com.stackoverflow.service.resource;

import java.security.Principal;
import java.sql.Timestamp;
import java.time.Clock;
import java.time.Instant;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

import javax.annotation.*;
import javax.ws.rs.*;
import javax.ws.rs.core.*;
import javax.ws.rs.core.Response.Status;

import com.stackoverflow.*;
import com.stackoverflow.json.view.*;
import com.codahale.metrics.annotation.*;
import com.fasterxml.jackson.annotation.JsonView;
import io.dropwizard.auth.Auth;
import com.gs.fw.common.mithra.finder.*;
import cool.klass.data.store.*;
import cool.klass.model.meta.domain.api.DomainModel;
import cool.klass.model.meta.domain.api.Klass;
import cool.klass.model.meta.domain.api.Multiplicity;
import cool.klass.model.meta.domain.api.property.DataTypeProperty;
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.databind.node.ObjectNode;
import cool.klass.deserializer.json.*;
import cool.klass.deserializer.json.type.*;
import cool.klass.reladomo.persistent.writer.*;
import cool.klass.model.meta.domain.api.projection.Projection;
import cool.klass.serialization.jackson.response.KlassResponseBuilder;

import org.eclipse.collections.api.factory.Maps;
import org.eclipse.collections.api.list.MutableList;
import org.eclipse.collections.api.map.MapIterable;
import org.eclipse.collections.impl.factory.Lists;
import org.eclipse.collections.impl.factory.primitive.LongSets;
import org.eclipse.collections.impl.set.mutable.*;
import org.eclipse.collections.impl.utility.*;

/**
 * Auto-generated by {@link cool.klass.generator.service.ServiceResourceGenerator}
 */
@Path("/")
public class QuestionVoteResource
{
    @Nonnull
    private final DomainModel domainModel;
    @Nonnull
    private final DataStore   dataStore;
    @Nonnull
    private final Clock       clock;

    public QuestionVoteResource(
            @Nonnull DomainModel domainModel,
            @Nonnull DataStore dataStore,
            @Nonnull Clock clock)
    {
        this.domainModel = Objects.requireNonNull(domainModel);
        this.dataStore   = Objects.requireNonNull(dataStore);
        this.clock       = Objects.requireNonNull(clock);
    }

    @Timed
    @ExceptionMetered
    @PUT
    @Path("/question/{questionId}/votes")
    @Produces(MediaType.APPLICATION_JSON)
    public void method0(
            @PathParam("questionId") Long questionId,
            @Nonnull @Auth Principal principal,
            @Nonnull @NotNull ObjectNode incomingInstance)
    {
        Klass klass = this.domainModel.getClassByName("QuestionVote");

        MutableList<String> errors = Lists.mutable.empty();
        MutableList<String> warnings = Lists.mutable.empty();
        ObjectNodeTypeCheckingValidator.validate(errors, incomingInstance, klass);
        RequiredPropertiesValidator.validate(
                errors,
                warnings,
                klass,
                incomingInstance,
                OperationMode.REPLACE);

        if (errors.notEmpty())
        {
            Response response = Response
                    .status(Status.BAD_REQUEST)
                    .entity(errors)
                    .build();
            throw new BadRequestException("Incoming data failed validation.", response);
        }

        if (warnings.notEmpty())
        {
            Response response = Response
                    .status(Status.BAD_REQUEST)
                    .entity(warnings)
                    .build();
            throw new BadRequestException("Incoming data failed validation.", response);
        }

        String    userPrincipalName  = principal.getName();
        Operation queryOperation     = QuestionVoteFinder.questionId().eq(questionId)
                .and(QuestionVoteFinder.createdById().eq(userPrincipalName));

        QuestionVoteList result = QuestionVoteFinder.findMany(queryOperation);

        if (result.isEmpty())
        {
            throw new ClientErrorException("Url valid, data not found.", Status.GONE);
        }


        Object persistentInstance = Iterate.getOnly(result);

        Instant            transactionInstant = Instant.now(this.clock);
        MutationContext    mutationContext    = new MutationContext(Optional.of(userPrincipalName), transactionInstant, Maps.immutable.empty());
        Klass              userKlass          = this.domainModel.getUserClass().get();
        IncomingUpdateDataModelValidator.validate(
                this.dataStore,
                userKlass,
                klass,
                mutationContext,
                persistentInstance,
                incomingInstance,
                errors,
                warnings);
        if (errors.notEmpty())
        {
            Response response = Response
                    .status(Status.BAD_REQUEST)
                    .entity(errors)
                    .build();
            throw new BadRequestException("Incoming data failed validation.", response);
        }
        if (warnings.notEmpty())
        {
            Response response = Response
                    .status(Status.BAD_REQUEST)
                    .entity(warnings)
                    .build();
            throw new BadRequestException("Incoming data failed validation.", response);
        }

        PersistentReplacer replacer           = new PersistentReplacer(mutationContext, this.dataStore);
        replacer.synchronize(klass, persistentInstance, incomingInstance);
    }

    @Timed
    @ExceptionMetered
    @DELETE
    @Path("/question/{questionId}/votes")
    @Produces(MediaType.APPLICATION_JSON)
    public void method1(
            @PathParam("questionId") Long questionId,
            @Nonnull @Auth Principal principal)
    {
        Klass klass = this.domainModel.getClassByName("QuestionVote");
        String    userPrincipalName  = principal.getName();
        Operation queryOperation     = QuestionVoteFinder.questionId().eq(questionId)
                .and(QuestionVoteFinder.createdById().eq(userPrincipalName));

        QuestionVoteList result = QuestionVoteFinder.findMany(queryOperation);

        if (result.isEmpty())
        {
            throw new ClientErrorException("Url valid, data not found.", Status.GONE);
        }



        Instant           transactionInstant = Instant.now(this.clock);
        MutationContext   mutationContext    = new MutationContext(Optional.of(userPrincipalName), transactionInstant, Maps.immutable.empty());
        PersistentDeleter deleter            = new PersistentDeleter(mutationContext, this.dataStore);

        this.dataStore.runInTransaction(() ->
        {
            for (int i = result.size() - 1; i >= 0; i--)
            {
                Object persistentInstance = result.get(i);
                deleter.deleteOrTerminate(klass, persistentInstance);
            }
        });
    }

    @Timed
    @ExceptionMetered
    @POST
    @Path("/vote")
    @Produces(MediaType.APPLICATION_JSON)
    public Response method2(
            @Nonnull @NotNull ObjectNode incomingInstance,
            @Nonnull @Context UriInfo uriInfo,
            @Nonnull @Auth Principal principal)
    {
        Klass klass = this.domainModel.getClassByName("QuestionVote");

        MutableList<String> errors = Lists.mutable.empty();
        MutableList<String> warnings = Lists.mutable.empty();
        ObjectNodeTypeCheckingValidator.validate(errors, incomingInstance, klass);
        RequiredPropertiesValidator.validate(
                errors,
                warnings,
                klass,
                incomingInstance,
                OperationMode.CREATE);

        if (errors.notEmpty())
        {
            Response response = Response
                    .status(Status.BAD_REQUEST)
                    .entity(errors)
                    .build();
            throw new BadRequestException("Incoming data failed validation.", response);
        }

        // Note: warnings are logged but do not cause request failure
        // TODO: Consider returning warnings in response headers

        String    userPrincipalName  = principal.getName();


        // Create the instance inside a transaction
        Instant transactionInstant = Instant.now(this.clock);
        MutationContext mutationContext = new MutationContext(Optional.of(userPrincipalName), transactionInstant, Maps.immutable.empty());
        PersistentCreator creator = new PersistentCreator(mutationContext, this.dataStore);
        MapIterable<DataTypeProperty, Object> resolvedKeys = creator.resolveKeysForCreate(klass, incomingInstance);
        ObjectNode finalIncomingInstance = incomingInstance;
        Object persistentInstance = this.dataStore.runInTransaction(transaction -> {
            Object instance = this.dataStore.instantiate(klass, resolvedKeys);
            creator.synchronize(klass, instance, finalIncomingInstance);
            this.dataStore.insert(instance);
            return instance;
        });

        MapIterable<DataTypeProperty, Object> allKeys = creator.resolveAllKeysAfterCreate(klass, resolvedKeys, persistentInstance);
        QuestionVoteList result = (QuestionVoteList) (List) this.dataStore.findByKeyReturningList(klass, allKeys);
        result.deepFetch(QuestionVoteFinder.createdBy());

        Projection projection = this.domainModel.getProjectionByName("QuestionVoteProjection");

        var responseBuilder = new KlassResponseBuilder(
                Iterate.getOnly(result),
                projection,
                Multiplicity.ONE_TO_ONE,
                transactionInstant);

        UriBuilder uriBuilder = uriInfo.getAbsolutePathBuilder();
        return Response.created(uriBuilder.build()).entity(responseBuilder.build()).build();
    }
}
