package com.stackoverflow.service.resource;

import java.security.Principal;
import java.sql.Timestamp;
import java.time.Clock;
import java.time.Instant;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

import javax.annotation.*;
import javax.ws.rs.*;
import javax.ws.rs.core.*;
import javax.ws.rs.core.Response.Status;

import com.stackoverflow.*;
import com.stackoverflow.json.view.*;
import com.codahale.metrics.annotation.*;
import com.fasterxml.jackson.annotation.JsonView;
import io.dropwizard.auth.Auth;
import com.gs.fw.common.mithra.finder.*;
import cool.klass.data.store.*;
import cool.klass.model.meta.domain.api.DomainModel;
import cool.klass.model.meta.domain.api.Klass;
import cool.klass.model.meta.domain.api.Multiplicity;
import cool.klass.model.meta.domain.api.property.DataTypeProperty;
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.databind.node.ObjectNode;
import cool.klass.deserializer.json.*;
import cool.klass.deserializer.json.type.*;
import cool.klass.reladomo.persistent.writer.*;

import org.eclipse.collections.api.factory.Maps;
import org.eclipse.collections.api.list.MutableList;
import org.eclipse.collections.api.map.MapIterable;
import org.eclipse.collections.impl.factory.Lists;
import org.eclipse.collections.impl.factory.primitive.LongSets;
import org.eclipse.collections.impl.set.mutable.*;
import org.eclipse.collections.impl.utility.*;

/**
 * Auto-generated by {@link cool.klass.generator.service.ServiceResourceGenerator}
 */
@Path("/")
public class TagResource
{
    @Nonnull
    private final DomainModel domainModel;
    @Nonnull
    private final DataStore   dataStore;
    @Nonnull
    private final Clock       clock;

    public TagResource(
            @Nonnull DomainModel domainModel,
            @Nonnull DataStore dataStore,
            @Nonnull Clock clock)
    {
        this.domainModel = Objects.requireNonNull(domainModel);
        this.dataStore   = Objects.requireNonNull(dataStore);
        this.clock       = Objects.requireNonNull(clock);
    }

    @Timed
    @ExceptionMetered
    @GET
    @Path("/tag/{name}")
    @Produces(MediaType.APPLICATION_JSON)
    @JsonView(TagProjection_JsonView.class)
    public Tag method0(
            @PathParam("name") String name)
    {
        // Tag

        Operation queryOperation     = TagFinder.name().eq(name);

        TagList result = TagFinder.findMany(queryOperation);
        // Deep fetch using projection TagProjection

        if (result.isEmpty())
        {
            throw new ClientErrorException("Url valid, data not found.", Status.GONE);
        }
        return Iterate.getOnly(result);
    }

    @Timed
    @ExceptionMetered
    @DELETE
    @Path("/tag/{name}")
    @Produces(MediaType.APPLICATION_JSON)
    public void method1(
            @PathParam("name") String name,
            @Nonnull @Auth Principal principal)
    {
        Klass klass = this.domainModel.getClassByName("Tag");
        String    userPrincipalName  = principal.getName();
        Operation queryOperation     = TagFinder.name().eq(name);

        TagList result = TagFinder.findMany(queryOperation);
        result.deepFetch(TagFinder.version());

        if (result.isEmpty())
        {
            throw new ClientErrorException("Url valid, data not found.", Status.GONE);
        }



        Instant           transactionInstant = Instant.now(this.clock);
        MutationContext   mutationContext    = new MutationContext(Optional.of(userPrincipalName), transactionInstant, Maps.immutable.empty());
        PersistentDeleter deleter            = new PersistentDeleter(mutationContext, this.dataStore);

        this.dataStore.runInTransaction(() ->
        {
            deleter.deleteAllOrTerminate(klass, result);
        });
    }

    @Timed
    @ExceptionMetered
    @GET
    @Path("/tag")
    @Produces(MediaType.APPLICATION_JSON)
    @JsonView(TagProjection_JsonView.class)
    public List<Tag> method2()
    {
        // Tag

        Operation queryOperation     = TagFinder.all();

        TagList result = TagFinder.findMany(queryOperation);
        // Deep fetch using projection TagProjection

        return result;
    }

    @Timed
    @ExceptionMetered
    @POST
    @Path("/tag")
    public Response method3(
            @Nonnull @NotNull ObjectNode incomingInstance,
            @Nonnull @Context UriInfo uriInfo,
            @Nonnull @Auth Principal principal)
    {
        Klass klass = this.domainModel.getClassByName("Tag");

        MutableList<String> errors = Lists.mutable.empty();
        MutableList<String> warnings = Lists.mutable.empty();
        ObjectNodeTypeCheckingValidator.validate(errors, incomingInstance, klass);
        RequiredPropertiesValidator.validate(
                errors,
                warnings,
                klass,
                incomingInstance,
                OperationMode.CREATE);

        if (errors.notEmpty())
        {
            Response response = Response
                    .status(Status.BAD_REQUEST)
                    .entity(errors)
                    .build();
            throw new BadRequestException("Incoming data failed validation.", response);
        }

        // Note: warnings are logged but do not cause request failure
        // TODO: Consider returning warnings in response headers

        String    userPrincipalName  = principal.getName();


        // Create the instance inside a transaction
        Instant transactionInstant = Instant.now(this.clock);
        MutationContext mutationContext = new MutationContext(Optional.of(userPrincipalName), transactionInstant, Maps.immutable.empty());
        PersistentCreator creator = new PersistentCreator(mutationContext, this.dataStore);
        MapIterable<DataTypeProperty, Object> resolvedKeys = creator.resolveKeysForCreate(klass, incomingInstance);
        ObjectNode finalIncomingInstance = incomingInstance;
        Object persistentInstance = this.dataStore.runInTransaction(transaction -> {
            Object instance = this.dataStore.instantiate(klass, resolvedKeys);
            creator.synchronize(klass, instance, finalIncomingInstance);
            this.dataStore.insert(instance);
            return instance;
        });

        return Response.noContent().build();
    }
}
