package cool.klass.test;

import java.sql.Timestamp;
import cool.klass.test.reladomo.readable.ReladomoReadableClassWithSystemTemporal;

/**
 * Auto-generated by {@link cool.klass.generator.reladomo.concrete.ReladomoConcreteClassGenerator}
 */
public class ClassWithSystemTemporal
        extends ClassWithSystemTemporalAbstract
        implements ReladomoReadableClassWithSystemTemporal
{
    public ClassWithSystemTemporal(Timestamp system)
    {
        super(system);
        // You must not modify this constructor. Reladomo calls this internally.
        // You can call this constructor. You can also add new constructors.
    }

    public ClassWithSystemTemporal()
    {
        this(ClassWithSystemTemporalFinder.system().getInfinityDate());
    }
}
