package cool.klass.test;

import java.sql.Date;
import java.sql.Timestamp;

import java.time.Instant;
import java.time.LocalDate;

/**
 * Auto-generated by {@link cool.klass.generator.reladomo.concrete.ReladomoConcreteClassGenerator}
 */
public class ClassWithDerivedProperty
        extends ClassWithDerivedPropertyAbstract
{
    public ClassWithDerivedProperty()
    {
        super();
        // You must not modify this constructor. Reladomo calls this internally.
        // You can call this constructor. You can also add new constructors.
    }

    public String getDerivedRequiredString()
    {
        // TODO implement derived property: derivedRequiredString
        return "ClassWithDerivedProperty derivedRequiredString 1 \u261D";
    }

    public int getDerivedRequiredInteger()
    {
        // TODO implement derived property: derivedRequiredInteger
        return 1;
    }

    public long getDerivedRequiredLong()
    {
        // TODO implement derived property: derivedRequiredLong
        return 100000000000L;
    }

    public double getDerivedRequiredDouble()
    {
        // TODO implement derived property: derivedRequiredDouble
        return 1.0123456789;
    }

    public float getDerivedRequiredFloat()
    {
        // TODO implement derived property: derivedRequiredFloat
        return 1.0123457f;
    }

    public boolean getDerivedRequiredBoolean()
    {
        // TODO implement derived property: derivedRequiredBoolean
        return true;
    }

    public Timestamp getDerivedRequiredInstant()
    {
        // TODO implement derived property: derivedRequiredInstant
        return Timestamp.from(Instant.parse("1999-12-31T23:59:00Z"));
    }

    public Date getDerivedRequiredLocalDate()
    {
        // TODO implement derived property: derivedRequiredLocalDate
        return Date.valueOf(LocalDate.parse("1999-12-31"));
    }

    public String getDerivedOptionalString()
    {
        // TODO implement derived property: derivedOptionalString
        return "ClassWithDerivedProperty derivedOptionalString 1 \u261D";
    }

    public int getDerivedOptionalInteger()
    {
        // TODO implement derived property: derivedOptionalInteger
        return 1;
    }

    public long getDerivedOptionalLong()
    {
        // TODO implement derived property: derivedOptionalLong
        return 100000000000L;
    }

    public double getDerivedOptionalDouble()
    {
        // TODO implement derived property: derivedOptionalDouble
        return 1.0123456789;
    }

    public float getDerivedOptionalFloat()
    {
        // TODO implement derived property: derivedOptionalFloat
        return 1.0123457f;
    }

    public boolean getDerivedOptionalBoolean()
    {
        // TODO implement derived property: derivedOptionalBoolean
        return true;
    }

    public Timestamp getDerivedOptionalInstant()
    {
        // TODO implement derived property: derivedOptionalInstant
        return Timestamp.from(Instant.parse("1999-12-31T23:59:00Z"));
    }

    public Date getDerivedOptionalLocalDate()
    {
        // TODO implement derived property: derivedOptionalLocalDate
        return Date.valueOf(LocalDate.parse("1999-12-31"));
    }
}
