[tools]
java = "temurin-21.0.6+7.0.LTS"
just = "1.40.0"
maven = "3.9.10"
node = "24.2.0"
"npm:markdownlint-cli" = "0.45.0"
"npm:strip-ansi-cli" = "4.0.0"
python = "3.12"

[env]
TERM = 'xterm-256color'
