logging:
  level: DEBUG
  loggers:
    org.eclipse.jetty: INFO
    com.stackoverflow: DEBUG
    com.gs.fw.common.mithra.sqllogs: DEBUG
    com.gs.fw.common.mithra.batch.sqllogs: DEBUG

server:
  detailedJsonProcessingExceptionMapper: true
