on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Generate Retype docs
        uses: retypeapp/action-build@latest
        with:
          # config: retype.yml is the default
          config: docs/retype.yml

      - name: Push to GitHub Pages
        uses: retypeapp/action-github-pages@latest
        if: github.event_name == 'push'
        with:
          # branch: retype is the default
          branch: retype
          update-branch: true
