#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
#set( $symbol_at = '@' )

set dotenv-filename := ".envrc"

group_id_with_slashes := "${packageInPathFormat}"

import ".just/console.just"
import ".just/maven.just"
import ".just/git.just"
import ".just/git-test.just"

# `just --list--unsorted`
default:
    @just --list --unsorted

# `mise install`
mise:
    mise install --quiet
    mise current

# clean (maven and git)
@clean: _clean-git _clean-maven _clean-m2

markdownlint:
    markdownlint --config .markdownlint.jsonc  --fix .

# Run all formatting tools for pre-commit
precommit: mvn
    uv tool run pre-commit run

# Override this with a command called `woof` which notifies you in whatever ways you prefer.
# My `woof` command uses `echo`, `say`, and sends a Pushover notification.
echo_command := env('ECHO_COMMAND', "echo")

build-first:
    git init
    git add -A
    git commit -m "Initial import."

    git mv gitignore .gitignore
    git mv .idea/gitignore .idea/.gitignore
    git commit -m "Move .gitignore in place."

build-second:
    git rm *-reladomo-pojos/src/main/java/{{group_id_with_slashes}}/DeleteMe*.java
    git commit -m "Remove DeleteMe*."

    git add -A
    git commit -m "Initial domain model."

    just install
    git add -A
    git commit -m "Initial code generation."
