on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  maven-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          key: maven-coverage-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2/repository
          restore-keys: |
            maven-coverage-
            maven-

      - uses: actions/setup-java@v4
        with:
          java-version-file: .tool-versions
          distribution: oracle

      - run: ./mvnw verify --activate-profiles jacoco-maven-plugin

      - uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Jacoco Code Coverage"
          update-comment: true
          min-coverage-overall: 0
          min-coverage-changed-files: 0

      - name: "Clean Maven cache"
        run: rm -rf ~/.m2/repository/cool/klass

  # Check if the new commits in a Pull Request contain a merge commit. If so, fail and print them out.
  forbid-merge-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: motlin/forbid-merge-commits-action@main

  reviewdog-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-shellcheck@v1.28.0
        with:
          reporter: github-pr-check
          fail_on_error: true
          filter_mode: nofilter
