name: Publish Retype docs to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  retype:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: retypeapp/action-build@latest
        with:
          # config: retype.yml is the default
          config: docs/retype.yml

      - uses: retypeapp/action-github-pages@latest
        with:
          # branch: retype is the default
          branch: retype
          update-branch: true
